iterations: 0
bucket_count: 0
global_time_limit: 0
base_name: prova
parameters:
  - - WORST-SOL
    - Constant: true
  - - KERNEL-GROWTH
    - Variable
  - - REMOVE-UNSET
    - Constant: true
  - - PROBLEM-KICKSTART
    - Variable
  - - DISTILL
    - Variable